In [1]:
# Import Pandas
import pandas as pd

In [2]:
# Load CSV Dataset
df = pd.read_csv("SalesDataset.csv")

In [4]:
# Display first 5 rows
# First 5 Rows
df.head()

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
0,1,2025-10-20,Aarav,45.0,Jaipur,Laptop,Electronics,4,30815.0,15,104771.0,Cash,Cancelled
1,2,2025-03-24,Aarav,51.0,Jaipur,Keyboard,Accessories,2,16883.0,10,30389.4,UPI,Processing
2,3,2025-03-13,Ayesha,42.0,Jaipur,Keyboard,Accessories,5,30438.0,5,144580.5,Card,Processing
3,4,2025-12-05,Ayesha,26.0,NaN,Phone,Electronics,8,40694.0,15,276719.2,UPI,Cancelled
4,5,2025-01-03,Kabir,26.0,Mumbai,Keyboard,Accessories,6,51097.0,5,291252.9,Cash,Cancelled

In [5]:
# Display last 5 rows
df.tail()

,OrderID,OrderDate,CustomerName,Age,City,Product,Category,Quantity,UnitPrice,Discount,TotalSales,PaymentMode,OrderStatus
1015,351,2025-12-17,Najrin,18.0,Chennai,Keyboard,Accessories,5,42333.0,10,190498.5,Cash,Delivered
1016,587,2025-08-14,Najrin,36.0,Mumbai,Laptop,Electronics,1,10956.0,0,10956.0,Cash,Cancelled
1017,778,2025-12-29,Ayesha,36.0,Chennai,Phone,Electronics,4,32689.0,10,117680.4,Card,Delivered
1018,150,2025-05-05,Diya,45.0,Jaipur,Keyboard,Accessories,4,25447.0,0,101788.0,Card,Processing
1019,537,2025-02-21,Rehan,32.0,Mumbai,Printer,Office,8,36305.0,15,246874.0,Card,Processing

In [6]:
# Display column names
df.columns

Index(['OrderID', 'OrderDate', 'CustomerName', 'Age', 'City', 'Product',
       'Category', 'Quantity', 'UnitPrice', 'Discount', 'TotalSales',
       'PaymentMode', 'OrderStatus'],
      dtype='str')